{% set name = "pymsgbox" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyMsgBox-{{ version }}.tar.gz
  sha256: 2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pymsgbox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asweigart/PyMsgBox
  license: BSD-3-Clause
  summary: A simple, cross-platform, pure Python module for JavaScript-like message boxes.
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jschueller
    - thewchan
